### PR TITLE
radio button selection support

### PR DESCRIPTION
**Pull request by robbiev**

### CODE REVIEW

**Comment by robbiev** [comment]
Rather than create a separate PR in andlabs/ui I thought it would be cleaner to include this in your PR as my change needs the updated `ui.h` too.

**Comment by emersion** [comment]
Yeah, thanks! LGTM, the only thing that seems missing is a `delete` call in `Destroy`, otherwise entries in the `radioButtons` map don't get cleared.

**Comment by robbiev** [comment]
Well spotted, I added the fix.

**Comment by emersion** [comment]
:+1:

**Pull request merged**
